name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        
    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy

    - name: Run local server
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestApp$ ./tests

    - name: Run DB
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestDB$ ./tests 
        
    - name: Run NextDate
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestNextDate$ ./tests 
        
    - name: Run DB
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestDB$ ./tests 
                
    - name: Run NextDate
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestNextDate$ ./tests 
    
    - name: Run AddTask
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestAddTask$ ./tests 

    - name: Run TestTasks
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestTasks$ ./tests

    - name: Run TestTask
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestTask$ ./tests

    - name: Run TestEditTask
      run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 100
          go test -run ^TestEditTask$ ./tests
